services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile

    ports:
      - "3000:3000"

    env_file:
      - ./backend/.env

    depends_on:
      - postgres

  postgres:
    image: postgres:17

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7256
      POSTGRES_DB: securebank

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
